### ISSUE TITLE
Overriding delimiter leads to inconsistent headers

### ISSUE THREAD

**Issue by franza** [jwerle/to-csv#8]
See example:

```javascript
var CSV = requrie('to-csv');
CSV.DELIMITER = ';'.charCodeAt(0);

var result = CSV([{ a: 1, b: 2 }]);
console.log(result);
```

This will output:

```
a,b
1;2
```

Instead of expected

```
a;b
1;2
```

It seems for me that the issue is in this line:

```javascript
return false !== opts.headers
        ? [].concat(headers.join(','), char(CSV.CHAR_NEWLINE)).concat(buf).filter(Boolean).join('')
        : buf.filter(Boolean).join('');
```

`headers` should be joined with `CSV.DELIMITER` instead of `','`.

**Comment by jwerle** [comment]
ah, nice catch. I'd happily accept a PR

**Comment by jwerle** [comment]
Fixed with https://github.com/jwerle/to-csv/commit/573bf847bc877f13672bd954ea40e13e5147b2a3
